# Generated by Django 2.1.4 on 2019-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('ordinary', '普通用户'), ('coder', '开发者用户'), ('manager', '管理员')], default='普通用户', max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
